var skimlinks_pub_id = '33330X911647';
var skimlinks_site = 'lifehacker.com';
var skimwords_hover_name = 'neutral';
var skimwords_horizontal_distance = 100;
var skimwords_vertical_distance = 100;
var skimlinks_exclude = Array('amazon.com');
var noskimwords = true;
var noskoupon = true;
var noskimproducts = true;
var skimwords_instant = true;
(function(){var assign_globals,attr,bind,contains_malencoded_pound,convert_url,create_class_re,create_request_str,data,encode_uri,escape_regexp,find_by_class,find_by_classname_re,find_unique_domains,fix_anchor,g_detect,g_has_been_called,g_hostname,g_html_root,g_http_re,g_impressions,g_included_classes,g_included_ids,g_loading_started,g_tracking_api_url,get_link_from_event,get_links,get_script,has_class,has_excluded_rels,is_allowed_domain,is_allowed_rel,is_div_blocked,is_excluded_domain,is_external_domain,is_merchant,
is_parents_blocked,is_tagged,json_stringify,local_stringify,non_affiliate_click,replace_href,rerun_skimlinks,send_through_sl,skim_init,skimlinks,skimlinks_callback,skimlinks_loader,sl_byrel,sl_exclude,sl_exrel,sl_go_domain,sl_google,sl_handlers,sl_noright,sl_settings,sl_sitename,sl_skimout,sl_tag_block,sl_target,sl_test,sl_tracking,strip_www,text,track_google_page_view,track_impressions,trim,__cookie,__country,__noimpressions,__noskim,__noskimlinks,__noskimwords,__pub_id,_location,_window,_this=this,
__hasProp=Object.prototype.hasOwnProperty;g_html_root=null;g_has_been_called=!1;g_hostname=g_included_ids=g_included_classes=null;g_impressions={pag:"",phr:[],pub:"",slc:0,swc:0,jsl:0,jsf:"",guid:"",uc:"",t:1};g_tracking_api_url="http://t.skimresources.com/api/";g_loading_started=(new Date).getTime();g_http_re=/http:/g;
g_detect=function(){var a;a=navigator.userAgent.toLowerCase();a=/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version)?[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+))?/.exec(a)||[];return{browser:a[1]||"",version:parseFloat(a[2])||0}}();__noskimlinks=__noskimwords=__noskim=__noimpressions=__pub_id=sl_handlers=sl_tag_block=sl_byrel=sl_exrel=sl_noright=sl_exclude=sl_test=sl_target=sl_skimout=sl_google=sl_go_domain=sl_sitename=sl_tracking=null;
__cookie=__country="";_window=this;_location=_window.location;sl_settings={default_excl_rels:["noskim","norewrite"],default_excl_domains:"*doubleclick.net,*mjxads.internet.com,*pgpartner.co.uk,*pgpartner.com,*pricegrabber.co.uk,*pricegrabber.com,*overture.com,*youtube.com".split(","),api_url:"http://r.skimresources.com/api/"};
assign_globals=function(){var a,b,c,d,e,f,h,g,i,j,k,l,m,n,o,p,q;g_html_root=null!=(a=document.getElementsByTagName("html"))?a[0]:void 0;g_included_classes=null!=(j=_window.skimlinks_included_classes)?j:[];g_included_ids=null!=(k=_window.skimlinks_included_ids)?k:[];g_hostname=strip_www(_location.hostname);sl_tracking=null!=(l=_window.skimlinks_tracking)?l:!1;sl_sitename=null!=(m=_window.skimlinks_site)?m:!1;sl_go_domain=null!=(n=_window.skimlinks_domain)?n:"go.redirectingat.com";sl_google=null!=(o=
_window.skimlinks_google)?o:!1;sl_skimout=null!=sl_google?sl_google:"skimout";sl_target=null!=(p=_window.skimlinks_target)?p:!1;sl_test=null!=(q=_window.sl_test)?q:!1;sl_exclude=null!=(b=_window.skimlinks_exclude)?b:[];sl_noright=null!=(c=_window.skimlinks_noright)?c:!1;sl_exrel=null!=(d=_window.skimlinks_exrel)?d:!1;sl_byrel=null!=(e=_window.skimlinks_byrel)?e:!1;sl_tag_block=null!=(f=_window.skimlinks_blocked_tag)?f:!1;sl_handlers=0;__pub_id=null!=(h=_window.skimlinks_pub_id)?h:"";__noimpressions=
null!=(g=_window.noimpressions)?g:!1;__noskimlinks=null!=(i=_window.noskimlinks)?i:!1;sl_tracking&&!/^[a-z0-9_\\|]+$/i.test(sl_tracking)&&(sl_tracking=!1);g_impressions.pub=__pub_id;g_impressions.uc=sl_tracking;"undefined"!==typeof assign_skimwords_globals&&null!==assign_skimwords_globals&&assign_skimwords_globals();g_included_classes.push("noskimlinks");return!0};strip_www=function(){var a;a=/^www\./i;return function(b){return b.replace(a,"")}}();
contains_malencoded_pound=function(a){return-1!==encodeURIComponent(a).indexOf("%C3%82%C2%A3")};fix_anchor=function(a){a=a.innerHTML.slice(0,4);if("http"===a||"www."===a)a.innerHTML="<span style='display:none!important;'>&nbsp;</span>";return!0};attr=function(a,b,c){var d;3<=arguments.length&&(a[b]=c);d=a[b];null==d&&(d=a.getAttribute(b));return d};data=function(a,b,c){arguments[1]="data-"+b;return attr.apply(this,arguments)};
bind=function(){return document.addEventListener?function(a,b,c){if(a&&(a.nodeName||a===_window))return a.addEventListener(b,c,!1)}:function(a,b,c){if(a&&(a.nodeName||a===_window))return a.attachEvent("on"+b,function(){return 7>g_detect.version&&!window.event?(setTimeout(function(){return c.call(a,window.event)},100),!0):c.call(a,window.event)})}}();text=function(a,b){var c;c=a.innerText||a.textContent||a.nodeValue;if(2<=arguments.length)a.innerText?a.innerText=b:a.textContent=b,c=b;return c};
trim=function(){var a,b;if(String.prototype.trim)return function(a){return null===a?"":String.prototype.trim.call(a)};a=/^\s+/;b=/\s+$/;/\S/.test("\u00a0")&&(a=/^[\s\xA0]+/,b=/[\s\xA0]+$/);return function(c){return null===c?"":c.toString().replace(a,"").replace(b,"")}}();
local_stringify=function(a){var b,c,d,e,f;if("object"===typeof a||a instanceof Array){e="";d=0;c=a instanceof Array;for(f in a)__hasProp.call(a,f)&&(b=a[f],0<d&&(e+=","),c?e+=json_stringify(b):(b=json_stringify(b),e+='"'+f+'":'+b),d++);return c?"["+e+"]":"{"+e+"}"}return"string"===typeof a?(b=a.replace(/"/g,'\\"',a),'"'+b+'"'):isNaN(a)?"null":a.toString()};json_stringify=function(){var a;return"undefined"!==typeof JSON&&null!==JSON&&JSON.stringify?(a=JSON.stringify,function(b){return a(b)}):local_stringify}();
escape_regexp=function(){var a;a=/[-[\]{}()*+?.,\\^$|#\s]/g;return function(b){return b.replace(a,"\\$&")}}();create_class_re=function(a){a=escape_regexp(a);return RegExp("\\b"+a+"\\b","i")};has_class=function(a,b){return a.className?create_class_re(b).test(a.className):!1};find_by_classname_re=function(a,b){var c,d,e,f,h;d=[];a.className&&b.test(a.className)&&d.push(a);h=a.childNodes;for(e=0,f=h.length;e<f;e++)c=h[e],d=d.concat(find_by_classname_re(c,b));return d};
find_by_class=function(){return document.createElement("div").getElementsByClassName?function(a,b){return has_class(a,b)?a:a.getElementsByClassName(b)}:function(a,b){var c;c=create_class_re(b);return find_by_classname_re(a,c)}}();is_parents_blocked=function(a){for(var b,c,d,e,a=a.parentNode;a&&a!==g_html_root;){c=a.id;for(d=0,e=g_included_classes.length;d<e;d++)if(b=g_included_classes[d],has_class(a,b))return!0;for(d=0,e=g_included_ids.length;d<e;d++)if(b=g_included_ids[d],c===b)return!0;a=a.parentNode}return!1};
is_div_blocked=function(a,b){var c,d;d=RegExp("\\b(?:(?:"+escape_regexp(b)+")|(?:noskim))\\b","i");for(c=a;null!=c&&c!==g_html_root;){if(c.className&&d.test(c.className))return!0;c=c.parentNode}return!1};
encode_uri=function(){var a,b;b=[function(){var b,d,e,f;e=[["%20","+"],["!","%21"],["'","%27"],["\\(","%28"],["\\)","%29"],["\\*","%2A"],["\\~","%7E"]];f=[];for(b=0,d=e.length;b<d;b++)a=e[b],f.push([RegExp(a[0],"g"),a[1]]);return f}()];return function(a){var d,e,f;d=encodeURIComponent(a);for(e=0,f=b.length;e<f;e++)a=b[e],d=d.replace(a[0],a[1]);return d}}();
convert_url=function(a,b){var c,d,e;has_class(a,"skimwords-link")?(e=attr(a,"data-skimwords-word"),c=attr(a,"data-skim-creative"),d=attr(a,"data-skim-product"),b="http://"+settings.sw_domain+"/?id="+__pub_id+""+(sl_tracking?"&xcust="+sl_tracking:"")+"&xs=2&url="+encode_uri(b)+"&xguid="+__cookie+"&xword="+(e?e:"")+"&xcreo="+(c?c:"")+"&xpid="+(d?d:"")+"&sref="+encode_uri(_location)):is_div_blocked(a,"skimlinks")||(c=attr(a,"data-skim-creative"),b="http://"+sl_go_domain+"/?id="+__pub_id+""+(sl_sitename?
"&site="+sl_sitename:"")+""+(sl_test?"&test="+sl_test:"")+""+(sl_tracking?"&xcust="+sl_tracking:"")+"&xs=1&url="+encode_uri(b)+"&xguid="+__cookie+"&xcreo="+(a&&null!=c?c:0)+"&sref="+encode_uri(_location));return b};get_link_from_event=function(a){var b;if((b=a.target||a.srcElement)&&3===b.nodeType)b=b.parentNode;if(b&&!b.href)b=a.currentTarget;return b};send_through_sl=function(a){a=get_link_from_event(a);replace_href(a);return!0};
replace_href=function(a){var b,c,d,e,f,h;f="msie"===g_detect.browser&&7>g_detect.version?1E4:100;b=!1;c=sl_google;if(a&&a.nodeName&&"IMG"===a.nodeName)a=a.parentNode;if(a){h=a.href;if("msie"===g_detect.browser&&8>=g_detect.version)e=a.innerHTML;(d=data(a,"skimlinks-href"))?b=!0:(d=convert_url(a,h),data(a,"skimlinks-href",d));c&&track_google_page_view(h);data(a,"skimlinks-orig-link")||(data(a,"skimlinks-orig-link",h),b=!1);a.href=d;if(e)a.innerHTML=e;setTimeout(function(){a.href=data(a,"skimlinks-orig-link");
if(e)a.innerHTML=e;return!0},f)}return b};is_merchant=function(a,b){var c,d,e;if(e=b.merchant_domains)for(c in e)if(__hasProp.call(e,c)&&(d=e[c],d===a))return!0;return!1};is_tagged=function(a){var b,c;if(!sl_tag_block)return!1;b=null!=a?a.previousSibling:void 0;if(!b)return!1;a=("["+sl_tag_block+"]").toLowerCase();c=text(b);c=c.toLowerCase();c=trim(c);b=c.lastIndexOf(a);return-1!==b&&b+a.length===c.length};
has_excluded_rels=function(){var a;a=null;return function(b){var c,d,e;if(!b)return!1;b=b.toLowerCase();if(a)return a[b];a={};c=sl_exrel?[sl_exrel]:[];c=c.concat(sl_settings.default_excl_rels);for(d=0,e=c.length;d<e;d++)b=c[d],a[b.toLowerCase()]=!0;return a[b]}}();is_allowed_rel=function(a){return!a||sl_byrel&&a===sl_byrel||!has_excluded_rels(a)};
is_excluded_domain=function(){var a;a=null;return function(b){var c,d,e,f;if(!a){a={};sl_sitename&&sl_exclude.push(sl_sitename);f=sl_exclude.concat(sl_settings.default_excl_domains);for(d=0,e=f.length;d<e;d++)c=f[d],a[c]=c.length}if(!b)return!1;for(c in a)if(__hasProp.call(a,c))if(d=a[c],0===c.indexOf("*")){if(c=c.substr(1),d-=1,e=b.lastIndexOf(c),-1!==e&&e===b.length-d)return!0}else if(b===c)return!0;return!1}}();
is_external_domain=function(){var a;a=/^\/\/|https?:\/\//i;return function(b,c){return a.test(b)&&(!c||-1===c.indexOf(g_hostname))&&(!g_hostname||-1===g_hostname.indexOf(".#{domain}"))}}();is_allowed_domain=function(a,b){return is_external_domain(a,b)&&!is_excluded_domain(b)};track_google_page_view=function(a){var b,c;b=_window.pageTracker;c=_window.urchinTracker;a="/"+sl_skimout+"/"+a;if(null!=b&&b._trackPageview)return b._trackPageview(a),!0;return c?(c(a),!0):!1};
create_request_str=function(){var a,b;a=encode_uri('},"pub"');b=""+g_tracking_api_url+"track.php?data=";return function(c){var d;d=b+encode_uri(json_stringify(g_impressions).replace(g_http_re,""));null!=c&&c.length&&(c.join(encode_uri(",")),d=d.replace(a,""+c+a));return[d,d.length]}}();
track_impressions=function(){var a,b,c,d,e,f,h,g;if(__noimpressions)return!1;f=(new Date).getTime()-g_loading_started;g=[];d=0;b=8E3;"msie"===g_detect.browser&&(b=2E3);g_impressions.slc=sl_handlers;g_impressions.swc="undefined"!==typeof sw_handlers&&null!==sw_handlers?sw_handlers:0;g_impressions.jsl=f;g_impressions.guid=__cookie;f=g_impressions.phr;g_impressions.phr=[];a=create_request_str();a=a[1];for(c in f)if(__hasProp.call(f,c)){e=f[c];e=json_stringify(e).replace(g_http_re,"");e=encode_uri('"'+
d+'":'+e);h=a+e.length+3*g.length;if(h>b)a=create_request_str(g),d=a[0],get_script(d,null,{async:!0}),g=[],d=0,g_impressions.t=0,a=create_request_str(),a=a[1];g.push(e);d++}get_script(create_request_str(g)[0],null,{async:!0});return!0};
non_affiliate_click=function(a){var b,c;c=new Date;b=c+300;a=get_link_from_event(a);a=encode_uri('{"pubcode":"'+__pub_id+'","referrer":"'+_location+'","site":"'+sl_sitename+'","url":"'+a.href+'","custom":"'+sl_tracking+'","product":"1"}');for(get_script(""+sl_settings.api_url+"?call=track&data="+a);c<b;)c=new Date;return!0};
get_script=function(a,b,c){var k;var d,e,f,h,g,i,j=this;null==c&&(c={});d=c.charset||null;i=c.target||null;k=null!=(e=c.async)?e:!0,c=k;e=null!=i&&i.document?i.document:document;f=e.getElementsByTagName("head")[0];g=e.createElement("script");h=!1;g.type="text/javascript";if(d)g.charset=d;g.onload=g.onreadystatechange=function(){var a;a=j.readyState;if(!h&&(!a||"complete"===a||"loaded"===a))if(g.onload=g.onreadystatechange=null,h=!0,b)return b.call(i)};g.async=!1!==c;g.src=a;f.appendChild(g);return g};
get_links=function(a){var b,c,d,e,f;b=null;a&&(b=RegExp("\\b"+escape_regexp(a)+"\\b","i"));e=document.getElementsByTagName("a");f=[];for(c=0,d=e.length;c<d;c++)a=e[c],a.href&&(!b||a.className&&b.test(a.className))&&f.push(a);return f};
skimlinks_callback=function(a){var b,c,d,e,f,h,g,i;e=get_links();c=g_included_classes.length||g_included_ids.length;if(a.country)__country=a.country;if(a.guid)__cookie=a.guid;for(g=0,i=e.length;g<i;g++)if(b=e[g],d=strip_www(b.hostname),h=trim(b.href),f=attr(b,"rel"),(!c||!is_parents_blocked(b))&&!is_tagged(b))if(is_merchant(d,a)){if(is_allowed_rel(f)){sl_target&&attr(b,"target",sl_target);if("msie"===g_detect.browser){if(contains_malencoded_pound(b))return!0;fix_anchor(b)}bind(b,"click",send_through_sl);
sl_handlers++;sl_noright||bind(b,"contextmenu",send_through_sl)}}else is_allowed_domain(h,d)&&is_allowed_rel(f)&&(sl_target&&attr(b,"target",sl_target),bind(b,"click",non_affiliate_click),sl_noright||bind(b,"contextmenu",send_through_sl));"undefined"!==typeof skimwords&&null!==skimwords&&!__noskimwords?skimwords():track_impressions();return!0};
find_unique_domains=function(){var a,b,c,d,e,f,h,g;e=get_links();c=[];d={};for(h=0,g=e.length;h<g;h++)a=e[h],b=strip_www(a.hostname),f=trim(a.href),a=attr(a,"rel"),is_allowed_domain(f,b)&&is_allowed_rel(a)&&b&&!d[b]&&(c.push(b),d[b]=!0);return c};skimlinks=function(){var a;assign_globals();__noskimlinks||(a=find_unique_domains(),a=encode_uri('{"pubcode":"'+__pub_id+'","domains":'+json_stringify(a)+"}"),a=""+sl_settings.api_url+"?callback=skimlinksApplyHandlers&data="+a,get_script(a));return!0};
skimlinks_loader=function(){if(g_has_been_called)return!1;g_has_been_called=!0;skimlinks();return!0};
skim_init=function(){return _window.jQuery?function(){return _window.jQuery(document).ready(function(){return skimlinks_loader()})}:function(){var a,b,c;b=function(){if(g_has_been_called)return!0;try{document.documentElement.doScroll("left")}catch(a){return setTimeout(b,50),!1}return skimlinks_loader()};a=function(){return document.addEventListener?function(){document.removeEventListener("DOMContentLoaded",a,!1);skimlinks_loader();return!0}:document.attachEvent?function(){document.detachEvent("onreadystatechange",
a);skimlinks_loader();return!0}:function(){skimlinks_loader();return!0}}();if("complete"===document.readyState)setTimeout(skimlinks_loader,1);else if(document.addEventListener)document.addEventListener("DOMContentLoaded",a,!1),_window.addEventListener("load",skimlinks_loader,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",a);_window.attachEvent("onload",skimlinks_loader);c=!1;try{c=null===_window.frameElement}catch(d){}document.documentElement.doScroll&&c&&b()}return!0}}();
rerun_skimlinks=function(){g_has_been_called=!1;skimlinks_loader();return!0};_window.skimlinksApplyHandlers=skimlinks_callback;_window.mugicPopWin=send_through_sl;_window.mugicRight=send_through_sl;_window.skimlinksReload=rerun_skimlinks;skim_init();
})();